#define SDL_iconv SDL_COMPAT_SDL_iconv
#define SDL_iconv_string SDL_COMPAT_SDL_iconv_string
#define SDL_main SDL_COMPAT_SDL_main
#define SDL_SetModuleHandle SDL_COMPAT_SDL_SetModuleHandle
#define SDL_RegisterApp SDL_COMPAT_SDL_RegisterApp
#define SDL_UnregisterApp SDL_COMPAT_SDL_UnregisterApp
#define SDL_SetError SDL_COMPAT_SDL_SetError
#define SDL_GetError SDL_COMPAT_SDL_GetError
#define SDL_ClearError SDL_COMPAT_SDL_ClearError
#define SDL_Error SDL_COMPAT_SDL_Error
#define SDL_CreateMutex SDL_COMPAT_SDL_CreateMutex
#define SDL_mutexP SDL_COMPAT_SDL_mutexP
#define SDL_mutexV SDL_COMPAT_SDL_mutexV
#define SDL_DestroyMutex SDL_COMPAT_SDL_DestroyMutex
#define SDL_CreateSemaphore SDL_COMPAT_SDL_CreateSemaphore
#define SDL_SemPost SDL_COMPAT_SDL_SemPost
#define SDL_SemWait SDL_COMPAT_SDL_SemWait
#define SDL_SemWaitTimeout SDL_COMPAT_SDL_SemWaitTimeout
#define SDL_SemTryWait SDL_COMPAT_SDL_SemTryWait
#define SDL_SemValue SDL_COMPAT_SDL_SemValue
#define SDL_DestroySemaphore SDL_COMPAT_SDL_DestroySemaphore
#define SDL_CreateCond SDL_COMPAT_SDL_CreateCond
#define SDL_CondSignal SDL_COMPAT_SDL_CondSignal
#define SDL_CondBroadcast SDL_COMPAT_SDL_CondBroadcast
#define SDL_CondWait SDL_COMPAT_SDL_CondWait
#define SDL_CondWaitTimeout SDL_COMPAT_SDL_CondWaitTimeout
#define SDL_DestroyCond SDL_COMPAT_SDL_DestroyCond
#define SDL_CreateThread SDL_COMPAT_SDL_CreateThread
#define SDL_ThreadID SDL_COMPAT_SDL_ThreadID
#define SDL_GetThreadID SDL_COMPAT_SDL_GetThreadID
#define SDL_WaitThread SDL_COMPAT_SDL_WaitThread
#define SDL_KillThread SDL_COMPAT_SDL_KillThread
#define SDL_RWFromFP SDL_COMPAT_SDL_RWFromFP
#define SDL_RWFromFile SDL_COMPAT_SDL_RWFromFile
#define SDL_RWFromMem SDL_COMPAT_SDL_RWFromMem
#define SDL_RWFromConstMem SDL_COMPAT_SDL_RWFromConstMem
#define SDL_AllocRW SDL_COMPAT_SDL_AllocRW
#define SDL_FreeRW SDL_COMPAT_SDL_FreeRW
#define SDL_ReadLE16 SDL_COMPAT_SDL_ReadLE16
#define SDL_ReadBE16 SDL_COMPAT_SDL_ReadBE16
#define SDL_ReadLE32 SDL_COMPAT_SDL_ReadLE32
#define SDL_ReadBE32 SDL_COMPAT_SDL_ReadBE32
#define SDL_ReadLE64 SDL_COMPAT_SDL_ReadLE64
#define SDL_ReadBE64 SDL_COMPAT_SDL_ReadBE64
#define SDL_WriteLE16 SDL_COMPAT_SDL_WriteLE16
#define SDL_WriteBE16 SDL_COMPAT_SDL_WriteBE16
#define SDL_WriteLE32 SDL_COMPAT_SDL_WriteLE32
#define SDL_WriteBE32 SDL_COMPAT_SDL_WriteBE32
#define SDL_WriteLE64 SDL_COMPAT_SDL_WriteLE64
#define SDL_WriteBE64 SDL_COMPAT_SDL_WriteBE64
#define SDL_AudioInit SDL_COMPAT_SDL_AudioInit
#define SDL_AudioQuit SDL_COMPAT_SDL_AudioQuit
#define SDL_AudioDriverName SDL_COMPAT_SDL_AudioDriverName
#define SDL_OpenAudio SDL_COMPAT_SDL_OpenAudio
#define SDL_PauseAudio SDL_COMPAT_SDL_PauseAudio
#define SDL_CloseAudio SDL_COMPAT_SDL_CloseAudio
#define SDL_GetAudioStatus SDL_COMPAT_SDL_GetAudioStatus
#define SDL_LockAudio SDL_COMPAT_SDL_LockAudio
#define SDL_UnlockAudio SDL_COMPAT_SDL_UnlockAudio
#define SDL_LoadWAV_RW SDL_COMPAT_SDL_LoadWAV_RW
#define SDL_FreeWAV SDL_COMPAT_SDL_FreeWAV
#define SDL_BuildAudioCVT SDL_COMPAT_SDL_BuildAudioCVT
#define SDL_ConvertAudio SDL_COMPAT_SDL_ConvertAudio
#define SDL_MixAudio SDL_COMPAT_SDL_MixAudio
#define SDL_CDNumDrives SDL_COMPAT_SDL_CDNumDrives
#define SDL_CDName SDL_COMPAT_SDL_CDName
#define SDL_CDOpen SDL_COMPAT_SDL_CDOpen
#define SDL_CDStatus SDL_COMPAT_SDL_CDStatus
#define SDL_CDPlayTracks SDL_COMPAT_SDL_CDPlayTracks
#define SDL_CDPlay SDL_COMPAT_SDL_CDPlay
#define SDL_CDPause SDL_COMPAT_SDL_CDPause
#define SDL_CDResume SDL_COMPAT_SDL_CDResume
#define SDL_CDStop SDL_COMPAT_SDL_CDStop
#define SDL_CDEject SDL_COMPAT_SDL_CDEject
#define SDL_CDClose SDL_COMPAT_SDL_CDClose
#define SDL_HasRDTSC SDL_COMPAT_SDL_HasRDTSC
#define SDL_HasMMX SDL_COMPAT_SDL_HasMMX
#define SDL_HasMMXExt SDL_COMPAT_SDL_HasMMXExt
#define SDL_Has3DNow SDL_COMPAT_SDL_Has3DNow
#define SDL_Has3DNowExt SDL_COMPAT_SDL_Has3DNowExt
#define SDL_HasSSE SDL_COMPAT_SDL_HasSSE
#define SDL_HasSSE2 SDL_COMPAT_SDL_HasSSE2
#define SDL_HasAltiVec SDL_COMPAT_SDL_HasAltiVec
#define SDL_GetAppState SDL_COMPAT_SDL_GetAppState
#define SDL_GetKeyState SDL_COMPAT_SDL_GetKeyState
#define SDL_GetModState SDL_COMPAT_SDL_GetModState
#define SDL_SetModState SDL_COMPAT_SDL_SetModState
#define SDL_GetKeyName SDL_COMPAT_SDL_GetKeyName
#define SDL_EnableKeyRepeat SDL_COMPAT_SDL_EnableKeyRepeat
#define SDL_GetKeyRepeat SDL_COMPAT_SDL_GetKeyRepeat
#define SDL_EnableUNICODE SDL_COMPAT_SDL_EnableUNICODE
#define SDL_VideoInit SDL_COMPAT_SDL_VideoInit
#define SDL_VideoQuit SDL_COMPAT_SDL_VideoQuit
#define SDL_VideoDriverName SDL_COMPAT_SDL_VideoDriverName
#define SDL_GetVideoSurface SDL_COMPAT_SDL_GetVideoSurface
#define SDL_GetVideoInfo SDL_COMPAT_SDL_GetVideoInfo
#define SDL_VideoModeOK SDL_COMPAT_SDL_VideoModeOK
#define SDL_ListModes SDL_COMPAT_SDL_ListModes
#define SDL_SetVideoMode SDL_COMPAT_SDL_SetVideoMode
#define SDL_UpdateRects SDL_COMPAT_SDL_UpdateRects
#define SDL_UpdateRect SDL_COMPAT_SDL_UpdateRect
#define SDL_Flip SDL_COMPAT_SDL_Flip
#define SDL_SetGamma SDL_COMPAT_SDL_SetGamma
#define SDL_SetGammaRamp SDL_COMPAT_SDL_SetGammaRamp
#define SDL_GetGammaRamp SDL_COMPAT_SDL_GetGammaRamp
#define SDL_SetColors SDL_COMPAT_SDL_SetColors
#define SDL_SetPalette SDL_COMPAT_SDL_SetPalette
#define SDL_MapRGB SDL_COMPAT_SDL_MapRGB
#define SDL_MapRGBA SDL_COMPAT_SDL_MapRGBA
#define SDL_GetRGB SDL_COMPAT_SDL_GetRGB
#define SDL_GetRGBA SDL_COMPAT_SDL_GetRGBA
#define SDL_CreateRGBSurface SDL_COMPAT_SDL_CreateRGBSurface
#define SDL_CreateRGBSurfaceFrom SDL_COMPAT_SDL_CreateRGBSurfaceFrom
#define SDL_FreeSurface SDL_COMPAT_SDL_FreeSurface
#define SDL_LockSurface SDL_COMPAT_SDL_LockSurface
#define SDL_UnlockSurface SDL_COMPAT_SDL_UnlockSurface
#define SDL_LoadBMP_RW SDL_COMPAT_SDL_LoadBMP_RW
#define SDL_SaveBMP_RW SDL_COMPAT_SDL_SaveBMP_RW
#define SDL_SetColorKey SDL_COMPAT_SDL_SetColorKey
#define SDL_SetAlpha SDL_COMPAT_SDL_SetAlpha
#define SDL_SetClipRect SDL_COMPAT_SDL_SetClipRect
#define SDL_GetClipRect SDL_COMPAT_SDL_GetClipRect
#define SDL_ConvertSurface SDL_COMPAT_SDL_ConvertSurface
#define SDL_UpperBlit SDL_COMPAT_SDL_UpperBlit
#define SDL_LowerBlit SDL_COMPAT_SDL_LowerBlit
#define SDL_FillRect SDL_COMPAT_SDL_FillRect
#define SDL_DisplayFormat SDL_COMPAT_SDL_DisplayFormat
#define SDL_DisplayFormatAlpha SDL_COMPAT_SDL_DisplayFormatAlpha
#define SDL_CreateYUVOverlay SDL_COMPAT_SDL_CreateYUVOverlay
#define SDL_LockYUVOverlay SDL_COMPAT_SDL_LockYUVOverlay
#define SDL_UnlockYUVOverlay SDL_COMPAT_SDL_UnlockYUVOverlay
#define SDL_DisplayYUVOverlay SDL_COMPAT_SDL_DisplayYUVOverlay
#define SDL_FreeYUVOverlay SDL_COMPAT_SDL_FreeYUVOverlay
#define SDL_GL_LoadLibrary SDL_COMPAT_SDL_GL_LoadLibrary
#define SDL_GL_GetProcAddress SDL_COMPAT_SDL_GL_GetProcAddress
#define SDL_GL_SetAttribute SDL_COMPAT_SDL_GL_SetAttribute
#define SDL_GL_GetAttribute SDL_COMPAT_SDL_GL_GetAttribute
#define SDL_GL_SwapBuffers SDL_COMPAT_SDL_GL_SwapBuffers
#define SDL_GL_UpdateRects SDL_COMPAT_SDL_GL_UpdateRects
#define SDL_GL_Lock SDL_COMPAT_SDL_GL_Lock
#define SDL_GL_Unlock SDL_COMPAT_SDL_GL_Unlock
#define SDL_WM_SetCaption SDL_COMPAT_SDL_WM_SetCaption
#define SDL_WM_GetCaption SDL_COMPAT_SDL_WM_GetCaption
#define SDL_WM_SetIcon SDL_COMPAT_SDL_WM_SetIcon
#define SDL_WM_IconifyWindow SDL_COMPAT_SDL_WM_IconifyWindow
#define SDL_WM_ToggleFullScreen SDL_COMPAT_SDL_WM_ToggleFullScreen
#define SDL_WM_GrabInput SDL_COMPAT_SDL_WM_GrabInput
#define SDL_SoftStretch SDL_COMPAT_SDL_SoftStretch
#define SDL_GetMouseState SDL_COMPAT_SDL_GetMouseState
#define SDL_GetRelativeMouseState SDL_COMPAT_SDL_GetRelativeMouseState
#define SDL_WarpMouse SDL_COMPAT_SDL_WarpMouse
#define SDL_CreateCursor SDL_COMPAT_SDL_CreateCursor
#define SDL_SetCursor SDL_COMPAT_SDL_SetCursor
#define SDL_GetCursor SDL_COMPAT_SDL_GetCursor
#define SDL_FreeCursor SDL_COMPAT_SDL_FreeCursor
#define SDL_ShowCursor SDL_COMPAT_SDL_ShowCursor
#define SDL_NumJoysticks SDL_COMPAT_SDL_NumJoysticks
#define SDL_JoystickName SDL_COMPAT_SDL_JoystickName
#define SDL_JoystickOpen SDL_COMPAT_SDL_JoystickOpen
#define SDL_JoystickOpened SDL_COMPAT_SDL_JoystickOpened
#define SDL_JoystickIndex SDL_COMPAT_SDL_JoystickIndex
#define SDL_JoystickNumAxes SDL_COMPAT_SDL_JoystickNumAxes
#define SDL_JoystickNumBalls SDL_COMPAT_SDL_JoystickNumBalls
#define SDL_JoystickNumHats SDL_COMPAT_SDL_JoystickNumHats
#define SDL_JoystickNumButtons SDL_COMPAT_SDL_JoystickNumButtons
#define SDL_JoystickUpdate SDL_COMPAT_SDL_JoystickUpdate
#define SDL_JoystickEventState SDL_COMPAT_SDL_JoystickEventState
#define SDL_JoystickGetAxis SDL_COMPAT_SDL_JoystickGetAxis
#define SDL_JoystickGetHat SDL_COMPAT_SDL_JoystickGetHat
#define SDL_JoystickGetBall SDL_COMPAT_SDL_JoystickGetBall
#define SDL_JoystickGetButton SDL_COMPAT_SDL_JoystickGetButton
#define SDL_JoystickClose SDL_COMPAT_SDL_JoystickClose
#define SDL_PumpEvents SDL_COMPAT_SDL_PumpEvents
#define SDL_PeepEvents SDL_COMPAT_SDL_PeepEvents
#define SDL_PollEvent SDL_COMPAT_SDL_PollEvent
#define SDL_WaitEvent SDL_COMPAT_SDL_WaitEvent
#define SDL_PushEvent SDL_COMPAT_SDL_PushEvent
#define SDL_SetEventFilter SDL_COMPAT_SDL_SetEventFilter
#define SDL_GetEventFilter SDL_COMPAT_SDL_GetEventFilter
#define SDL_EventState SDL_COMPAT_SDL_EventState
#define SDL_LoadObject SDL_COMPAT_SDL_LoadObject
#define SDL_LoadFunction SDL_COMPAT_SDL_LoadFunction
#define SDL_UnloadObject SDL_COMPAT_SDL_UnloadObject
#define SDL_GetTicks SDL_COMPAT_SDL_GetTicks
#define SDL_Delay SDL_COMPAT_SDL_Delay
#define SDL_SetTimer SDL_COMPAT_SDL_SetTimer
#define SDL_AddTimer SDL_COMPAT_SDL_AddTimer
#define SDL_RemoveTimer SDL_COMPAT_SDL_RemoveTimer
#define SDL_Linked_Version SDL_COMPAT_SDL_Linked_Version
#define SDL_Init SDL_COMPAT_SDL_Init
#define SDL_InitSubSystem SDL_COMPAT_SDL_InitSubSystem
#define SDL_QuitSubSystem SDL_COMPAT_SDL_QuitSubSystem
#define SDL_WasInit SDL_COMPAT_SDL_WasInit
#define SDL_Quit SDL_COMPAT_SDL_Quit
#define SDL_GetWMInfo SDL_COMPAT_SDL_GetWMInfo
#define SDL12COMPAT_GetWindow SDL_COMPAT_SDL12COMPAT_GetWindow

#ifndef HAVE_ICONV
#undef SDL_iconv_t
#define SDL_iconv_t SDL_COMPAT_SDL_iconv_t
#undef SDL_iconv_open
#define SDL_iconv_open SDL_COMPAT_SDL_iconv_open
#undef SDL_iconv_close
#define SDL_iconv_close SDL_COMPAT_SDL_iconv_close
#endif

#ifndef HAVE_MALLOC
#undef SDL_malloc
#define SDL_malloc SDL_COMPAT_SDL_malloc
#endif

#ifndef HAVE_CALLOC
#undef SDL_calloc
#define SDL_calloc SDL_COMPAT_SDL_calloc
#endif

#ifndef HAVE_REALLOC
#undef SDL_realloc
#define SDL_realloc SDL_COMPAT_SDL_realloc
#endif

#ifndef HAVE_FREE
#undef SDL_free
#define SDL_free SDL_COMPAT_SDL_free
#endif

#ifndef HAVE_GETENV
#undef SDL_getenv
#define SDL_getenv SDL_COMPAT_SDL_getenv
#endif

#ifndef HAVE_PUTENV
#undef SDL_putenv
#define SDL_putenv SDL_COMPAT_SDL_putenv
#endif

#ifndef HAVE_QSORT
#undef SDL_qsort
#define SDL_qsort SDL_COMPAT_SDL_qsort
#endif

#ifndef HAVE_MEMSET
#undef SDL_memset
#define SDL_memset SDL_COMPAT_SDL_memset
#endif

#ifndef HAVE_MEMCPY
#undef SDL_memcpy
#define SDL_memcpy SDL_COMPAT_SDL_memcpy
#endif

#ifndef HAVE_REVCPY
#undef SDL_revcpy
#define SDL_revcpy SDL_COMPAT_SDL_revcpy
#endif

#ifndef HAVE_MEMCMP
#undef SDL_memcmp
#define SDL_memcmp SDL_COMPAT_SDL_memcmp
#endif

#ifndef HAVE_STRLEN
#undef SDL_strlen
#define SDL_strlen SDL_COMPAT_SDL_strlen
#endif

#ifndef HAVE_STRLCPY
#undef SDL_strlcpy
#define SDL_strlcpy SDL_COMPAT_SDL_strlcpy
#endif

#ifndef HAVE_STRLCAT
#undef SDL_strlcat
#define SDL_strlcat SDL_COMPAT_SDL_strlcat
#endif

#ifndef HAVE_STRDUP
#undef SDL_strdup
#define SDL_strdup SDL_COMPAT_SDL_strdup
#endif

#ifndef HAVE__STRREV
#undef SDL_strrev
#define SDL_strrev SDL_COMPAT_SDL_strrev
#endif

#ifndef HAVE__STRUPR
#undef SDL_strupr
#define SDL_strupr SDL_COMPAT_SDL_strupr
#endif

#ifndef HAVE__STRLWR
#undef SDL_strlwr
#define SDL_strlwr SDL_COMPAT_SDL_strlwr
#endif

#ifndef HAVE_STRCHR
#undef SDL_strchr
#define SDL_strchr SDL_COMPAT_SDL_strchr
#endif

#ifndef HAVE_STRRCHR
#undef SDL_strrchr
#define SDL_strrchr SDL_COMPAT_SDL_strrchr
#endif

#ifndef HAVE_STRSTR
#undef SDL_strstr
#define SDL_strstr SDL_COMPAT_SDL_strstr
#endif

#ifndef HAVE__LTOA
#undef SDL_ltoa
#define SDL_ltoa SDL_COMPAT_SDL_ltoa
#endif

#ifndef HAVE__ULTOA
#undef SDL_ultoa
#define SDL_ultoa SDL_COMPAT_SDL_ultoa
#endif

#ifndef HAVE_STRTOL
#undef SDL_strtol
#define SDL_strtol SDL_COMPAT_SDL_strtol
#endif

#ifndef HAVE_STRTOUL
#undef SDL_strtoul
#define SDL_strtoul SDL_COMPAT_SDL_strtoul
#endif

#ifndef HAVE__I64TOA
#undef SDL_lltoa
#define SDL_lltoa SDL_COMPAT_SDL_lltoa
#endif

#ifndef HAVE__UI64TOA
#undef SDL_ulltoa
#define SDL_ulltoa SDL_COMPAT_SDL_ulltoa
#endif

#ifndef HAVE__STRTOI64
#undef SDL_strtoll
#define SDL_strtoll SDL_COMPAT_SDL_strtoll
#elif !defined(HAVE_STRTOLL)
#undef SDL_strtoll
#define SDL_strtoll SDL_COMPAT_SDL_strtoll
#endif

#ifndef HAVE__STRTOUI64
#undef SDL_strtoull
#define SDL_strtoull SDL_COMPAT_SDL_strtoull
#elif !defined(HAVE_STRTOULL)
#undef SDL_strtoull
#define SDL_strtoull SDL_COMPAT_SDL_strtoull
#endif

#ifndef HAVE_STRTOD
#undef SDL_strtod
#define SDL_strtod SDL_COMPAT_SDL_strtod
#endif

#ifndef HAVE_STRCMP
#undef SDL_strcmp
#define SDL_strcmp SDL_COMPAT_SDL_strcmp
#endif

#ifndef HAVE_STRNCMP
#undef SDL_strncmp
#define SDL_strncmp SDL_COMPAT_SDL_strncmp
#endif

#ifndef HAVE_STRCASECMP
#undef SDL_strcasecmp
#define SDL_strcasecmp SDL_COMPAT_SDL_strcasecmp
#elif !defined(HAVE__STRICMP)
#undef SDL_strcasecmp
#define SDL_strcasecmp SDL_COMPAT_SDL_strcasecmp
#endif

#ifndef HAVE_STRNCASECMP
#undef SDL_strncasecmp
#define SDL_strncasecmp SDL_COMPAT_SDL_strncasecmp
#elif !defined(HAVE__STRNICMP)
#undef SDL_strcasecmp
#define SDL_strcasecmp SDL_COMPAT_SDL_strcasecmp
#endif

#ifndef HAVE_SSCANF
#undef SDL_sscanf
#define SDL_sscanf SDL_COMPAT_SDL_sscanf
#endif

#ifndef HAVE_SNPRINT
#undef SDL_snprintf
#define SDL_snprintf SDL_COMPAT_SDL_snprintf
#endif

#ifndef HAVE_VSNPRINTF
#undef SDL_vsnprintf
#define SDL_vsnprintf SDL_COMPAT_SDL_vsnprintf
#endif